### ISSUE TITLE
Document new functions

### ISSUE THREAD

**Issue by parth-dassana** [dassana-io/enterprise-docs#43]
[Issue created from Slack message on #query](https://dassana-corp.slack.com/archives/C02SJQRKL82/p1653332619064099)

New features in query, will document these eventually, not well tested:
• `COALESCE(&lt;field | literal&gt;, ...)` function: only allows fields which are not arrays or nested in arrays. if used in select then can be referenced in group-by/order-by using alias
• `JSON_QUERY_ARRAY( [$ | &lt;field&gt;], '$.<http://json.path.to|json.path.to>.array')` function: allows extracting an array in JSON to native array.
• `ARRAY_UNNEST( &lt;field | function&gt; )`  function: unnest, i.e create 1 row per element in the input field/function which is a native array, look at above function. eg: `select array_unnest(json_query_array($, '$.resources')) from aws_cloudtrail`
Experimental: `ANY VALUE CONTAINS` where predicate - similar to FTS. This can be slow, let me know your data sets and queries when you hit query time outs.
Syntax: `$*` is short hand for `any value` , `[]` wrapping means one of the options
```[ ANY VALUE | $* ] CONTAINS &lt;literal&gt;
[ ANY VALUE | $* ] CONTAINS [ ANY | ALL | NONE ] (&lt;literal-list&gt;, ...)
[ ANY VALUE | $* ] CONTAINS [ ANY | ALL | NONE ] [ LIKE | ILIKE ] &lt;like-pattern&gt;```
Example
```WHERE ANY VALUE CONTAINS 'some-text'
WHERE $* CONTAINS ALL ('text-1', 'text-2')```


Created by @yatin

Reported by @p

**Comment by yatin-dassana** [comment]
Done.
https://github.com/dassana-io/enterprise-docs/pull/45
