### ISSUE TITLE
Hyperlinks in docs are not redirected to the expected pages.

### ISSUE THREAD

**Issue by deepak-dassana** [dassana-io/enterprise-docs#56]
**Steps to reproduce:**

1. On query page click on ? icon 
2. Click on 'Docs' from the drop down
3. It lands on https://docs.dassana.cloud/query/intro/
4. All the Hyperlinks on this page are navigating wrong URLs

**Expected result:**

1. When clicked on "The schema aws_cloudtrail is simply the source id set under `Sources.`" Hyperlink, it should redirect to https://docs.dassana.cloud/app-store/intro
2. When clicked on "You can learn more about SLQ `here.`" Hyperlink, it should redirect to https://docs.dassana.cloud/query/SLQ
3. When clicked on "More sample queries are available `here.`" Hyperlink, it should redirect to https://docs.dassana.cloud/query/sample-queries

**Actual result:**

1. When clicked on "The schema aws_cloudtrail is simply the source id set under `Source`" Hyperlink, it redirects to https://docs.dassana.cloud/query/app-store/intro
2. When clicked on "You can learn more about SLQ `here.`" Hyperlink, it redirects to https://docs.dassana.cloud/query/intro/SLQ
3. When clicked on "More sample queries are available `here.`" Hyperlink, it redirects to https://docs.dassana.cloud/query/intro/sample-queries

https://images.zenhubusercontent.com/444636752/f15f1c8c-caab-415a-834f-ce9aaad8a46f/screen_recording_2022_11_30_at_6_15_39_pm.mov

**Comment by parth-dassana** [comment]
Done and tested in prod

**Comment by parth-dassana** [comment]
For some weird reason relative paths don't work in prod (even though they used to). Converted relative paths to absolute paths.
